[project]
name = "pyperformance_bm_json_dumps_opt"
requires-python = ">=3.8"
dependencies = ["pyperf", "ujson"]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "json_dumps_opt"
tags = "serialize"
